### ISSUE TITLE
有一个问题，如果在vuex中调用http.js里的axios方法，例子里的http.js无法获得vuex的状态了

### ISSUE THREAD

**Issue by hank2718** [superman66/vue-axios-github#10]

**Comment by superman66** [comment]
能否提供下你的代码？

**Comment by aaawhz** [comment]
如果http文件中  , axios 都去判断token的话, 那不是把那些不需要登录, 就可以访问的页面也给拦截了?

比如首页  说明页面

**Comment by aaawhz** [comment]
因为有时候, 其他不需要登录的页面, 也需要通过 axios获取数据来展示;  

比如淘宝网站, 不登录也是可以访问商品列表和搜索的.

**Comment by aaawhz** [comment]
所以是不是在 axios 的配置 config中 也需要判断 to.meta.requireAuthor ; 如果没有的话, 就不需要判断token了.

**Comment by superman66** [comment]
对于不需要token的接口请求，就不会在 Header 添加 token 字段。这样你不登录，照样还是可以访问接口。
http 中只是判断，如果本地存在 token 就将其加入到 Header 中，这样把登录状态的判断移交到后端。

**Comment by aaawhz** [comment]
意思是有 localstorage 有 token就提交;  至于访问这个数据是否需要登录, 由后台来判断,  

如果这个接口, 需要登录, 后台就会判断token是否过期;

如果这个接口游客也可以访问, 就直接返回数据, 不验证token?

**Comment by superman66** [comment]
是的。走 oAuth2.0 流程一般都是通过 token，后端判断用户状态及接口的权限。
