### ISSUE TITLE
build后dist目录下缺失静态文件

### ISSUE THREAD

**Issue by notreami** [superman66/vue-axios-github#11]
build后dist目录下只存在js文件。图标、html等静态资源没有复制进去。

**Comment by superman66** [comment]
该项目 webpack 配置用的是 `vue-cli` 生成的 `webpack-simple` 模板。所以 build 功能比较简单。
如果你要完整的构建功能，可以使用 `webpack` 模板来生成功能更完整的项目。
具体见：https://github.com/vuejs/vue-cli
