### ISSUE TITLE
后端401时，axios没能拦截到未授权信息

### ISSUE THREAD

**Issue by c89** [superman66/vue-axios-github#15]
`// http response 拦截器
axios.interceptors.response.use(
    response => {
        return response;
    },
    error => {
        if (error.response) {
            switch (error.response.status) {
                case 401:
                    // 返回 401 清除token信息并跳转到登录页面
                    store.commit(types.LOGOUT);
                    router.replace({
                        path: 'login',
                        query: {redirect: router.currentRoute.fullPath}
                    })
            }
        }
        return Promise.reject(error.response.data)   // 返回接口返回的错误信息
    });`
error.response undefined

**Comment by superman66** [comment]
后端都返回401了，为啥 `error.response` 为 undefined。
错误原因不够明显。建议打断点，输出整个 error 对象。
还有，你提问的时候，代码能格式化一下吗？虽然是我自己写的代码，但看起来也老费劲了。

**Comment by gbbyuluo** [comment]
我这是这种问题，error打印出来是network error

**Comment by superman66** [comment]
network error 应该是网络问题啊。
而且 error.response 没值的话，我觉得你应该找后端，让其接口返回值

**Comment by superman66** [comment]
@gbbyuluo @c89 如果没有问题的话，我把 issue 关了。有问题的话，你们再开启吧。
