### ISSUE TITLE
我之前也用vueResource使用过,后面发现有点问题.

### ISSUE THREAD

**Issue by zWingz** [superman66/vue-axios-github#2]
按照这个思路
是通过判断vuex里面的token是否存在来允许是否进入该路由.
我当时的需求是通过判断权限.可以说也是从vuex里面拿的数据
但有个问题就是
当按了F5刷新.
这时候进入router.forEach是比 app.beforeCreated要早执行的
这时候是不存在store里面的相关信息.所以就直接跳去login.
也是说每次按F5都要重新登陆一遍.
不知道你的会不会有这种情况.

**Comment by superman66** [comment]
有遇到，所以每次刷新的时候需要重新从localStorage中获取，然后用存入state中。见代码：
[https://github.com/superman66/vue-axios-github/blob/master/src/router.js#L37-L40](https://github.com/superman66/vue-axios-github/blob/master/src/router.js#L37-L40)
