### ISSUE TITLE
您好，用您这个方法发送请求时报错403是怎么回事呢

### ISSUE THREAD

**Issue by chenxiong666** [superman66/vue-axios-github#20]
![qq 20171110163802](https://user-images.githubusercontent.com/31265809/32649594-96d3e908-c635-11e7-8abf-4125c20f39f3.png)

**Comment by superman66** [comment]
根据报错信息来看，应该是跨域问题吧。你先把跨域解决了再试试

**Comment by chenxiong666** [comment]
后端刚刚告诉我他们跨域没解决好，还有就是那个自定义header为什么在浏览器中只能看见名字，不能看到保存在header中的token

**Comment by superman66** [comment]
没有明白你的问题？只能再浏览器中看到名字，不能看到token是什么意思？

**Comment by chenxiong666** [comment]
我的意思是不是将token放在header里了吗 为什么在浏览器中看不到，只能显示自定义header的名称

**Comment by superman66** [comment]
那是不是你的token值为空啊

**Comment by chenxiong666** [comment]
我的token不是空啊 我输出过，但是浏览器里出现的是这样的
Access-Control-Request-Headers:authorization
Access-Control-Request-Method:POST
然后报错
 Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by superman66** [comment]
这个应该是后端没配置正确。

**Comment by chenxiong666** [comment]
大佬有没有空帮我看一下啊，我没用过这个，后台又说他们配置好了，我不确定是不是我写错了，方不方便加QQ帮我看下

**Comment by chenxiong666** [comment]
好了，刚刚确定是后台原因了
