### ISSUE TITLE
Axios token

### ISSUE THREAD

**Issue by jarvan4dev** [superman66/vue-axios-github#21]
按照库主的做法，刷新页面后vuex状态丢失，原来的token不是都丢了吗？

**Comment by superman66** [comment]
所以有个步骤是在页面刷新的时候，将 token 从本地 存储取出，重新复制到 vuex 的过程

**Comment by jarvan4dev** [comment]
在哪一块呢？

**Comment by superman66** [comment]
https://github.com/superman66/vue-axios-github/blob/master/src/router.js#L40
