### ISSUE TITLE
关于token存值的疑问

### ISSUE THREAD

**Issue by AlanWenhao** [superman66/vue-axios-github#22]
## 为什么在router.js 里面要根据 `localStrorage` 里面有没有 token 重新给state赋值 token
https://github.com/superman66/vue-axios-github/blob/master/src/router.js#L37

## 我的疑问
不能直接在 Line 48 这样判断吗？
```
if (localStrorage.getItem('token')) {
    next();
}
```

## 我的理解
Line 37的做法其实就是每次重载页面把 `token` 存在了 `state` 里面，是为了方便存在 state 里面的token 以后使用 ？

## 如果有时间请帮忙解答一下我的疑惑

**Comment by superman66** [comment]
你的理解是对的。重新赋值就是为了方便在全局都能通过  store.state.token 的方式获取到 token。
直接按照你说的那么判断也可以，只不过是在其他地方如果要获取到 token 的时候，就得通过 `localStrorage.getItem('token')` 这种方式来获取了。
但是都通过 localStroage 来赋值取值的话，就跟 vuex 的理念有点不同了。

**Comment by AlanWenhao** [comment]
@superman66 
了解了，谢谢解答👻
