### ISSUE TITLE
关闭页签的时候怎么处理掉localstorage

### ISSUE THREAD

**Issue by Kemper-Diao** [superman66/vue-axios-github#24]
localstorage这边是永久存储的，网页关闭的时候你这边是怎么处理掉localstorage中的token。
用sessionstorage会不会好点

**Comment by superman66** [comment]
具体用 sessionStorage 还是用 localStorage 取决于你们产品对token的时效限制。我这个 demo 是没有处理，默认永久有效的，因为后端会去判断该 token 是否过期，如果过期的话，前端依然能够进行拦截，跳转到对应的登录页面。

**Comment by Kemper-Diao** [comment]
谢谢解答
