### ISSUE TITLE
生成 Github Personal Token 后，使用  Github Personal Token 登录，无法登录，自动重定向到了 https://github.com/settings/tokens/new

### ISSUE THREAD

**Issue by zzlw** [superman66/vue-axios-github#28]
生成 Github Personal Token 后，使用  Github Personal Token 登录，无法登录，自动重定向到了 https://github.com/settings/tokens/new

**Comment by superman66** [comment]
用  enter 键登录试试，下面那个按钮时跳转到生成 token 的页面
