### ISSUE TITLE
嵌套路由时，子路由需要重复设置meta:{requireAuth:true}

### ISSUE THREAD

**Issue by tracy2zhang** [superman66/vue-axios-github#4]
`{
      path: '/parent',
      name: 'parent',
      component: Parent,
      meta: {
        requireAuth: true
      },
      children: [
        {
          name: 'child',
          path: 'child',
          component: Child
        }
      ]
    }`
当访问/parent/child的时候并没有执行权限验证，所以建议在beforeEach中的判断由to.meta.requireAuth改为to.matched.some(r => r.meta.requireAuth)，这样的话父路由设置requireAuth后子路由就不用设置了
个人愚见，错误之处还请指正😝

**Comment by superman66** [comment]
多谢指出~你的这种做法是正确的，我稍后更新下代码。
