### ISSUE TITLE
axios为什么要封装到promise里面？

### ISSUE THREAD

**Issue by CommanderXL** [superman66/vue-axios-github#5]
`axios`里面本来就是用`promise`进行封装的，为什么还要重新在`promise`里面再封装一次呢？

**Comment by superman66** [comment]
多谢提醒。你说得对，在这里进行多一层的封装似乎显得没有必要，而且多余。
之所以多一层封装是因为可以在这里统一对数据做进一步的处理（虽然这个项目并没有用到）
