### ISSUE TITLE
请问token怎么后台配置跨域请求！

### ISSUE THREAD

**Issue by Niofh** [superman66/vue-axios-github#6]
我用了axios，也是跟着楼主配置axios，java怎么设置跨域请求，每次跨域请求都报405！！感觉很苦逼啊！

**Comment by notreami** [comment]
这个难道不是spring的问题嘛？各大搜索引擎应该都很容易搜索到解决方案

**Comment by superman66** [comment]
@notreami 我也觉得这种问题不应该到这里来提issue的
