### ISSUE TITLE
token 401判断

### ISSUE THREAD

**Issue by aaawhz** [superman66/vue-axios-github#7]
这个token 是sessionId 吧
每次http请求, cookie都会带上sessionId
验证没通过 接口也能返回401

如果http头的authorization 带上 sid,   
cookie 的sid 后台是不是就不用判断了, 
那要后台修改判断方式吗, 会不会降低安全性, 因为cookie字段可以用httpOnly保护起来, 

而存储在vuex 或者 sessionStorage中, 给了xss机会 ;

**Comment by superman66** [comment]
感谢@aaawhz 提出的issue。
第一点：关于验证没通过,不知道你指的是哪种类型的没通过？一般情况应该是当前token失效时，后端才应该返回401.
第二点：关于token的存储是采用cookie还是 Web Storage。
cookie能防止XSS没错，但是也会存在CSRF问题。相比CSRF而言，XSS更加容易防范。
这是我的看法，欢迎交流~
