### ISSUE TITLE
用户输入了错误的token提交时页面会先跳转到Frepository这个页面，然后再跳回Login页面，有办法规避这个问题吗

### ISSUE THREAD

**Issue by ghylc** [superman66/vue-axios-github#8]

**Comment by superman66** [comment]
在这个项目中暂时无法解决。因为提交token的过程只是模拟登录，并不涉及接口请求，无法真正判断该token是否有效。只能通过请求`https://api.github.com/user/repos`拿到http code来判断。
如果是真实项目中，你可以通过判断登录接口的返回值来做下一步的判断和跳转。

**Comment by ghylc** [comment]
哦，了解了，谢谢
